@startuml
start

:User interacts with YouTube video;

if (Play Video?) then (yes)
    :Create PlayCommand;
    :User executes PlayCommand;
    :VideoPlayer plays video;
    :Notify all observers about playback status;
endif

if (Pause Video?) then (yes)
    :Create PauseCommand;
    :User executes PauseCommand;
    :VideoPlayer pauses video;
    :Notify all observers about playback status;
endif

if (Adjust Volume?) then (yes)
    :User specifies new volume level;
    :Create VolumeCommand;
    :User executes VolumeCommand;
    :VideoPlayer sets new volume level;
    :Notify all observers about volume change;
endif

if (Fast Forward or Rewind?) then (yes)
    :User specifies seconds to scrub;
    if (Fast Forward) then (yes)
        :Create FastForwardCommand;
        :User executes FastForwardCommand;
        :VideoPlayer fast-forwards video;
    else (Rewind)
        :Create RewindCommand;
        :User executes RewindCommand;
        :VideoPlayer rewinds video;
    endif
    :Notify all observers about playback position;
endif

if (Add Comment?) then (yes)
    :User writes comment;
    :Video adds comment to comment list;
    :Notify all observers about new comment;
endif

if (Reply to Comment?) then (yes)
    :User writes reply;
    :Create ReplyCommand;
    :User executes ReplyCommand;
    :Comment adds reply;
    :Notify all observers about new reply;
endif

stop
@enduml
